# 数组
## 数组是一种广泛存在的数据结构，不仅仅是在一些通用的编程语言里，甚至在excel里也存在。
## 其数学含义是向量，以及由向量组成的矩阵。这意味着所有的向量和矩阵的数学特性均可以在numpy里面实现，这个特点和matlab非常相似
## 其实际作用在于能够把一组数据进行通用化处理



In [ ]:
#导入numpy
import numpy as np

In [4]:
#单维数组
a = np.arange(10)

#查看数组对象类型，构成元素的类型，以及数组的维度
print(type(a))
print(a.dtype)
print(a.shape)

<class 'numpy.ndarray'>
int32
(10,)


In [6]:
#多维数组
m = np.array([np.arange(4),np.arange(4)])

print(m)
print(m.shape)

[[0 1 2 3]
 [0 1 2 3]]
(2, 4)


In [10]:
##多维数组元素选取
m = np.array([np.arange(1,5),np.arange(5,9)])

###选取第二行第四列的数据，同样的，数组里面的序数是从0开始计数的
print(m[1,3])

8

In [19]:
##多维数组切片
m = np.arange(10)
print(m)
###切取第四至第六个元素（4，5，6号元素)，规则和原生的列表对象相似
print(m[4:7])
###以步长为2的方式选取元素
print(m[::2])
###翻转数组
print(m[::-1])

[0 1 2 3 4 5 6 7 8 9]
[4 5 6]
[0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]


# 基于数组的一些运算

In [27]:
#矩阵乘法
m = np.array([[1,2,3,4,5],[6,6,6,6,6]])
n = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
print(m.shape)
print(n.shape)
print(np.matmul(m,n))


(2, 5)
(5, 2)
[[ 95 110]
 [150 180]]


In [21]:
#计算行列式
##生成一个方阵
m = np.array([[1,2],[3,4]])

#导入线性代数相关的方法
from numpy import linalg

#计算行列式的值
linalg.det(m)

##有了行列式，意味着我们可以计算任意维度的超平面相交形成的n维体的体积了。


-2.0000000000000004

In [25]:
#计算特征值
m = np.array([[1,0,0],[0,2,0],[0,0,3]])
linalg.eig(m)
#返回的对象为一个数组，其中第一维是其特征值，第二维是其特征向量组

(array([1., 2., 3.]), array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

## 可以发现，其实numpy可以当做一个功能非常强大的计算器，